### ISSUE TITLE
Pawns not using the replimat termial dispite starving and having no other food source

### ISSUE THREAD

**Issue by TheStrongWill** [sumghai/Replimat#27]
[Südl. Thidinum-Föderation.zip](https://github.com/sumghai/Replimat/files/3964393/Sudl.Thidinum-Foderation.zip)

Well what the titel says. I use no listed incompatibel mods but still a lot of them. I leave my savefile here fou you if you want to look into the modlist there.
I get no errors or anything. My pawn just don't use it

**Comment by sumghai** [comment]
Before we begin, I want to point out that sending me an entire savefile is very impractical, as it took a long time for the 46.4 MB file to load in Notepad++. In the future, I suggest sending me your ModsConfig.xml instead, as that also provides a modlist in a more manageable file.

Also, rather than sending me a modlist to figure out, I recommend that you try to narrow down the problem yourself first - start by loading only Core and Replimat to confirm that the basic setup works without errors, then slowly add and test your other mods one-by-one until you find out which mod is conflicting with Replimat.

That being said, having looked at your modlist now:

* Pawn Rules is **_incompatible_** with Replimat. This was stated quite clearly in the Steam Workshop description.

* Try moving Replimat closer to the top of the mod load order.

**Comment by TheStrongWill** [comment]
Hey Robin Chang,
I'm sorry for sending you an impractical file and for forgetting to search
for the error myself. I now did a little bit of testing myself and found
out the following:
The mod work on my PC with ANY combination of all my mods installed, not
including Pawn Rules. (In the savefile I send you I already deinstalled
this mod)
The tipp that worked was moving the mod up the top of the loading order.
Sorry again for the trubble and thank you very much for your help.
Fabrice Schöneberger

Am So., 15. Dez. 2019 um 02:04 Uhr schrieb Robin Chang <
notifications@github.com>:
