### ISSUE TITLE
Terminals don't work with Common Sense mod

### ISSUE THREAD

**Issue by shiuanyue** [sumghai/Replimat#28]
Other devices are normal, Replimat Terminal cannot be used

**Comment by shiuanyue** [comment]
After testing, incompatible with the [common sense]

**Comment by shiuanyue** [comment]
But placing [common sense] MOD behind Replimat will not cause problems

**Comment by sumghai** [comment]
This is because Replimat uses Harmony patching to modify vanilla food utils and jobdrivers, by adding the Terminals as an additional food source that pawns would check for when they search for meals. 

I suspect that Common Sense is also modifying the same utils and jobdrivers in an incompatible manner. But since you mentioned that loading Common Sense after Replimat fixes this issue, then I can simply make a note of this in the Steam Workshop and Ludeon Forums descriptions.
