### ISSUE TITLE
Animal Feeding Issues

### ISSUE THREAD

**Issue by Arcalane** [sumghai/Replimat#59]
**Describe the bug:**  
Colony animals are attempting to feed from human replimat terminals, spamming the console with errors and not actually getting any food. This constantly pings/flickers the powernet for the operating cost, and also since they don't get fed but keep trying to feed there, they eventually collapse from exhaustion. This can be resolved by temporarily forbidding the terminal.

**Expected behavior:**  
Animals to either eat regular meals, loose food, or use a petfeeder.

**Steps to reproduce:**  
1. Assemble a functional replimat system.
2. Have colony animals. Have observed this occurring with wolves and cats, but assume it can happen with any animal.
3. Watch them ping the console until they collapse from exhaustion.

**Additional information:**
```
JobDriver threw exception in initAction for pawn Wolf_Arctic3339646 driver=JobDriver_Ingest (toilIndex=1) driver.job=(Ingest (Job_14244107) A=Thing_ReplimatTerminal2658052)
System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.FoodUtility.HasHumanMeatEatingRequiredPrecept (RimWorld.Ideo ideo) [0x00000] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
  at Replimat.ReplimatUtility.GenerateIngredients (Verse.Thing meal, RimWorld.Ideo ideo) [0x0020e] in <3c77b63583da4d9a896b68fcaebf234c>:0 
  at Replimat.Building_ReplimatTerminal.TryDispenseFood (Verse.Pawn eater, Verse.Pawn getter) [0x00072] in <3c77b63583da4d9a896b68fcaebf234c>:0 
  at Replimat.Patches.Harmony_Toils_Ingest_TakeMealFromDispenser+<>c__DisplayClass0_0.<Prefix>b__0 () [0x0004e] in <3c77b63583da4d9a896b68fcaebf234c>:0 
  at Verse.AI.JobDriver.TryActuallyStartNextToil () [0x001de] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Verse.AI.JobUtility:TryStartErrorRecoverJob (Verse.Pawn,string,System.Exception,Verse.AI.JobDriver)
Verse.AI.JobDriver:TryActuallyStartNextToil ()
Verse.AI.JobDriver:ReadyForNextToil ()
Verse.AI.JobDriver:Notify_PatherArrived ()
Verse.AI.Pawn_PathFollower:PatherArrived ()
Verse.AI.Pawn_PathFollower:StartPath (Verse.LocalTargetInfo,Verse.AI.PathEndMode)
Verse.AI.Toils_Goto/<>c__DisplayClass1_0:<GotoThing>b__0 ()
Verse.AI.JobDriver:TryActuallyStartNextToil ()
Verse.AI.JobDriver:ReadyForNextToil ()
(wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.StartJob_Patch2 (Verse.AI.Pawn_JobTracker,Verse.AI.Job,Verse.AI.JobCondition,Verse.AI.ThinkNode,bool,bool,Verse.ThinkTreeDef,System.Nullable`1<Verse.AI.JobTag>,bool,bool)
Verse.AI.Pawn_JobTracker:TryFindAndStartJob ()
(wrapper dynamic-method) Verse.AI.Pawn_JobTracker:Verse.AI.Pawn_JobTracker.EndCurrentJob_Patch6 (Verse.AI.Pawn_JobTracker,Verse.AI.JobCondition,bool,bool)
Verse.AI.Pawn_JobTracker:JobTrackerTick ()
Verse.Pawn:Tick ()
(wrapper dynamic-method) Verse.TickList:Verse.TickList.Tick_Patch2 (Verse.TickList)
(wrapper dynamic-method) Verse.TickManager:Verse.TickManager.DoSingleTick_Patch1 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
Verse.Game:UpdatePlay ()
Verse.Root_Play:Update ()
```

## System and Game Configuration
**Operating System:** Microsoft Windows 10 (64-bit)
**Physical RAM:** 16.0 GB
**RimWorld base game version:** 1.3.3200
**RimWorld DLCs loaded:** Royalty, Ideology
**Replimat mod version:** 1.2.13
**Replimat mod downloaded from:** Steam
**Your mod list:** *Extremely long.* [Google doc here](https://docs.google.com/document/d/1XaRxCLRiMj7icO1oovQ5S93GL_KyqZa_xxqatJSCvdw/edit?usp=sharing). All mods are their latest versions, subbed via steam, aside from Bright Flames which is a local mod.

## Declaration
I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies (all auto-updated via steam)
- [x] I am NOT running any mods with known incompatibilities with Replimat (there are no known issues at this time)
- [ ] I have narrowed down my modlist to the fewest mods needed to cause this issue (see closing statement below)
- [x] I have confirmed that the issue does not happen if Replimat is disabled (it hinges on the terminal being there...)
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before (nothing similar, though at a glance it looks like it might be related to #58 and/or #54)
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

## Closing statement
I have yet to figure out exactly which mod is causing this. This occurs in both a "fresh" (post-ideology) colony and a pre-ideology colony that has been brought forward. Initially I thought it was due to changes in my modlist that I'd made after starting the new colony with ideology, but this isn't the case, as it's occuring in the pre-ideology colony which hasn't had its modlist changed significantly. All mods (except two) are up-to-date with rimworld to my knowledge.

My pre-ideology colony's ideologion is 99% vanilla save for its Relics, which are from VIE-Relics & Artefacts, and one of its rituals which is a psychic channelling ritual from Party Hard - Psycast Rituals. Memes are Loyalist/Collectivist/Proselytizer. All precepts are vanilla ideology. Ideological structure, Frontier culture, Techist style. I have however used devmode to tinker with the precepts, so unexpected combinations may be occurring here; notably, I have Cannibalism "Acceptable", which I don't think is valid for the current meme setup. *Edit:* Quick testing has shown that changing this to "Abhorrent" hasn't helped.

I realize the size of the modlist is going to make it a nightmare to figure out the exact cause, but it was fine until a couple of updates ago and the fact it's happening on my pre-ideology colony still is the most unusual part. Post-ideology they were feeding just fine (even with an ideology!) and something has changed _very_ recently (i.e. within the last month or two) to break that.

**Comment by sumghai** [comment]
Animals should *never* be using Replimat Terminals intended for humans. 

In my own tests with just Harmony, Core, Royalty, Ideology and Replimat, colony animals successfully ignored Terminals in favor of Animal Feeders, while humanlike pawns continued to use Terminals to replicate ideo-compatible meals as usual.

It is most likely that you are running a third-party mod that fundamentally changes the base game's food-related utilities/jobgivers/jobdrivers, whereas Replimat only prefixes/postfixes existing logic. My co-author @Dubwise56 has made it absolutely clear to me Replimat cannot support such behavior-altering mods, because they often use destructive code detours that Replimat's Harmony patches cannot target.

You are currently running 340 mods, any of which could be causing this incompatibility. You will need to rapidly narrow down your modlist by conducting a binary search, a common technique for finding conflicting RimWorld mods:

1) Take your current modlist
2) Keep Harmony and Replimat enabled for all tests
3) Disable half of all your other mods (make note which mods you have turned off)
4) Start a new savegame in dev mode
5) Test to see if the issue occurs
 a. If it does, the conflicting mod is in your (current) active list
 b. If it doesn't, your current half-list of mods are "known good" moods,  
 the conflicting mod is in your (current) inactive list; swap your active half with your inactive half
6) Split your (remaining) modlist in half
7) Repeat Steps 1 through to 6 until you have narrowed down to the one mod conflicting with Replimat

![binarySearch_340mods](https://user-images.githubusercontent.com/4993380/144690665-344df658-d316-445d-81a4-291772882401.png)

340 mods should take less than 10 iterations to search through, and the search process will get faster towards the end as you are loading fewer mods each time.

**Comment by Arcalane** [comment]
After ~three passes, I've got it. Animals Logic added the ability for animals to use Paste Dispensers. The tooltip for this feature claims a conflict is 'extremely unlikely', but I guess this is the one case it will still happen.

Fortunately the mod provides an in-game toggle option for this setting which takes immediate effect.

Tested by stripping everything down to just core, royalty, ideology, harmony, replimat, and animalslogic.

**Comment by sumghai** [comment]
Okay, I just peeked at the source code for Animal Logic - it's using a transpiler on `FoodUtility.BestFoodSourceOnMap`, whereas Dubs and I simply prefix the same method. Neither mods are doing destructive code detours, so *in theory* this isn't a code conflict.

What I think is happening is that once Animals Logic allows animals to use Paste Dispensers and Replimats, Replimat (as of **v1.2.11, released **13 November 2021**) looks for the pawn's ideology when choosing meal ingredients. And since animal pawns don't have ideologies, Replimat throws a hissy fit.

The solution might be for Replimat to run extra checks to see if a pawn has an ideology, and if it doesn't, Replimat shouldn't run the ideo-related meal ingredient code. I'll try something tonight.

**Comment by sumghai** [comment]
@Arcalane Please temporarily disable the Steam version of Replimat, and manually install the following development build into your `<Steam Installation Directory>\steamapps\common\RimWorld\Mods` directory

https://github.com/sumghai/Replimat/archive/81eeece8b996e22eb454cb6148c50dc1ff59ba76.zip

I've verified with a modlist consisting of Harmony, Core, Royalty, Ideology, Replimat and Animals Logic that both humanlike and animal pawns now can use Replimat Terminals without errors.

Could you please confirm the fix works on your end? (For both the test save and your main savegame)

**Comment by Arcalane** [comment]
Will do. Give me a bit.

**Comment by Arcalane** [comment]
I don't have any test saves, but loading it up with my old colony and reenabling the dispenser feeding option lead to uh... this;
![image](https://user-images.githubusercontent.com/1179240/144715109-3cc7257e-da40-4c03-ae9d-30b6dda41aa2.png)

Seems to be working. I guess if people don't want animals using fullsize replimat terminals they can just disable the feeder option in animals logic instead.

**Comment by sumghai** [comment]
Yeah, that's because the Replimat Terminals' building class is extended from the base game's Nutrient Paste Dispenser behaviour, and Terminals by design have the highest food source optimality.

Animals Logic's author justified animals being able to operate paste dispensers by "pushing a button", whereas I'd imagine Replimat Terminals are operated by a series of touchscreen button presses or a voice command. Best not to think too much about animals being capable of such complex behaviour...

I'll mark this one as fixed.

**Comment by Arcalane** [comment]
Parrots, man. Parrots. Teach a parrot to peck a button and say "tea, earl grey, hot" and before you know it, giant pile of teacups and your silo's empty.

If you need to, handwave it with something about the terminal having baby/child/animal proofing functions where it can scan whatever's trying to use it and just spits out something "safe" for them. Easy.

**Comment by sumghai** [comment]
Yeah, fair point :)
