### ISSUE TITLE
Replimat Cadaver Processor fails with AlienCorpseHasOrganicFlesh

### ISSUE THREAD

**Issue by ChiefCurtains** [sumghai/Replimat#61]
**Describe the bug:**  

When building a Cadaver Processor, while using the Kobolds of the Rim mod, the Cadaver Processor disappears on completing construction and cannot be built in GodMode. An error message appears (seen in Additional Information).

**Expected behavior:**  

The Cadaver Processor to be built and function normally. 

**Steps to reproduce:**  

1. Install Kobolds of the Rim
2. Build Replimat
3. Review Debug Log

**Additional information:**

```
Failed to find Verse.ThingDef named Bone. There are 10335 defs of this type loaded.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
Verse.DefDatabase`1<Verse.ThingDef>:GetNamed (string,bool)
Verse.ThingDef:Named (string)
Replimat.ModCompatibility:AlienCorpseHasOrganicFlesh (Verse.ThingDef)
Replimat.Building_ReplimatCorpseRecycler/<>c:<GetParentStoreSettings>b__21_1 (Verse.ThingDef)
System.Collections.Generic.HashSet`1<Verse.ThingDef>:RemoveWhere (System.Predicate`1<Verse.ThingDef>)
Replimat.Building_ReplimatCorpseRecycler:GetParentStoreSettings ()
RimWorld.StorageSettings:.ctor (RimWorld.IStoreSettingsParent)
Replimat.Building_ReplimatCorpseRecycler:PostMake ()
(wrapper dynamic-method) Verse.ThingMaker:Verse.ThingMaker.MakeThing_Patch2 (Verse.ThingDef,Verse.ThingDef)
RimWorld.Designator_Build:DesignateSingleCell (Verse.IntVec3)
(wrapper dynamic-method) Verse.DesignatorManager:Verse.DesignatorManager.ProcessInputEvents_Patch1 (Verse.DesignatorManager)
(wrapper dynamic-method) RimWorld.MapInterface:RimWorld.MapInterface.HandleMapClicks_Patch1 (RimWorld.MapInterface)
(wrapper dynamic-method) RimWorld.UIRoot_Play:RimWorld.UIRoot_Play.UIRootOnGUI_Patch2 (RimWorld.UIRoot_Play)
(wrapper dynamic-method) Verse.Root:Verse.Root.OnGUI_Patch1 (Verse.Root)
```

## System and Game Configuration
**Operating System:** 
Windows 10 (64 Bit)
**Physical RAM:** 
64.0 GB
**RimWorld base game version:** 
Most recent stable build
**RimWorld DLCs loaded:** 
Ideology, Royalty
**Replimat mod version:** 
Most recent stable version
**Replimat mod downloaded from:** 
Steam
**Your mod list:** 
Harmony(brrainz.harmony)[mv:1.2.0.0]: 0Harmony(2.2.0),
HarmonyMod(1.2.0),HugsLib(UnlimitedHugs.HugsLib)[ov:9.0.1]: 0Harmony(av:2.2.0,fv:1.2.0.1)
HugsLib(av:1.0.0,fv:9.0.1)
Replimat(sumghai.Replimat_copy)[mv:1.2.15]: Replimat(1.0.0)
Kobolds of the Rim(Goob.Kobolds): (no assemblies)

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Thanks for your report, @ChiefCurtains! I have reproduced the bug on my end.

As per your recent Steam Workshop comment, it does look like the `Kobold_Bone` item/weapon was put into the `CorpsesHumanlike` category,  which causes the Replimat Cadaver Reprocessor to throw a fit because the latter expects actual corpses with meat. I concur that it is indeed a very odd design choice by the mod authors, given that they planned to implement bones as a crafting resource for weapons/armor/furniture.

And it appears that the Kobold mod authors are no longer actively maintaining the mod:

![Screenshot 2022-02-19 120105](https://user-images.githubusercontent.com/4993380/154785374-d2d9af7a-e902-43d9-abcc-9c5726ed213a.png)

The best thing to do for now would be for Replimat to simply patch Kobolds and move bones to a different item category.
