### ISSUE TITLE
Error with Mutasalt and Mutacheese from Pawnmorpher

### ISSUE THREAD

**Issue by Daedalus2788** [sumghai/Replimat#69]
**Describe the bug:**  
Two red errors show up in the logs on startup, regarding Mutasalt and Mutacheese from Pawnmorpher. It hast something to do with the Patch in Replimat, because when I delete the Pawnmorpher Patch in the Replimat directory, the error vanishes. Strangely, the error only occurs, when loaded with exactly these mods below:
[Replimat](https://steamcommunity.com/sharedfiles/filedetails/?id=1715402900) together with [Pawnmorpher](https://steamcommunity.com/sharedfiles/filedetails/?id=1786466855), [Vanilla Cooking Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=2134308519) and [Remote Tech](https://steamcommunity.com/sharedfiles/filedetails/?id=761379469).

**Expected behavior:**  
No errors should occur. Mutasalt and Mutacheese Patch fails.

**Steps to reproduce:**  
1. Activate the following Mods (and their dependencies): [Replimat](https://steamcommunity.com/sharedfiles/filedetails/?id=1715402900), [Pawnmorpher](https://steamcommunity.com/sharedfiles/filedetails/?id=1786466855), [Vanilla Cooking Expanded](https://steamcommunity.com/sharedfiles/filedetails/?id=2134308519), [Remote Tech](https://steamcommunity.com/sharedfiles/filedetails/?id=761379469).
2. Start the Game
3. Open Logs - Error should be seen there

**Additional information:**
I don't really know, why Remote Tech interferes, but it definetly has to be loaded for the errors to occur. Full Log: [Log](https://gist.github.com/HugsLibRecordKeeper/9498ad088014bcc7fb366970fd441876) 
The Errors in question:
_Could not resolve cross-reference to Verse.ThingDef named Mutasalt (wanter=disallowedIngredients) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
Could not resolve cross-reference to Verse.ThingDef named Mutacheese (wanter=disallowedIngredients) 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)_

## System and Game Configuration
**Operating System:**  Microsoft Windows 10 (64-bit)
**Physical RAM:** 64.0 GB
**RimWorld base game version:** 1.3.3389
**RimWorld DLCs loaded:** Royalty, Ideology
**Replimat mod version:** v1.3.4
**Replimat mod downloaded from:** Steam
**Your mod list:**
Harmony(brrainz.harmony)[mv:1.3.0.0]: 0Harmony(2.2.1), HarmonyMod(1.3.0)
Core(Ludeon.RimWorld): (no assemblies)
Better Log - Fix your errors with style(bs.betterlog): BetterLog(1.0.0)
Royalty(Ludeon.RimWorld.Royalty): (no assemblies)
Ideology(Ludeon.RimWorld.Ideology): (no assemblies)
HugsLib(UnlimitedHugs.HugsLib)[ov:9.0.1]: 0Harmony(av:2.2.1,fv:1.2.0.1), HugsLib(av:1.0.0,fv:9.0.1)
Humanoid Alien Races(erdelf.HumanoidAlienRaces): 0Harmony(av:2.2.1,fv:2.2.0), AlienRace(1.0.0)
Remote Tech(UnlimitedHugs.RemoteTech): RemoteTech(av:2.1.0,fv:2.4.0)
Replimat(sumghai.Replimat)[mv:1.3.4]: Replimat(1.0.0)
Vanilla Expanded Framework(OskarPotocki.VanillaFactionsExpanded.Core): 0MultiplayerAPI(av:0.3.0,fv:0.3.0), CompOversizedWeapon(1.0.0), ExplosiveTrailsEffect(1.0.7140.31563), GraphicCustomization(1.0.0), HeavyWeapons(1.0.0), KCSG(av:1.1.2,fv:22.7.14), MVCF(1.0.0), NoCamShakeExplosions(1.0.0), OPToxic(1.0.0), Outposts(av:3.0.0,fv:1.0.0), PipeSystem(1.0.1), RecipeInheritance(1.0.0), Reloading(1.1.0), RRO(1.0.0), SmokingGun(1.0.0), VanillaStorytellersExpanded(1.0.0), VanillaWeaponsExpandedLaser(1.0.0), VFECore(av:1.1.7,fv:1.1.9), VWEMakeshift(1.0.0)
Vanilla Cooking Expanded(VanillaExpanded.VCookE): AchievementsExpanded(1.3.7862.41411), VanillaCookingExpanded(1.0.0)
Pawnmorpher(tachyonite.pawnmorpherpublic)[mv:1.12.2]: 0MultiplayerAPI(av:0.3.0,fv:0.1.0), Pawnmorph(av:1.10.0,fv:1.10.0)

## Declaration

I hereby verify that:
- [x] I am running the latest version of the game, Replimat and its dependencies
- [x] I am NOT running any mods with known incompatibilities with Replimat 
- [x] I have narrowed down my modlist to the fewest mods needed to cause this issue
- [x] I have confirmed that the issue does not happen if Replimat is disabled
- [x] I have searched the issue tracker and confirmed no-one else has reported my issue before
- [x] I understand that my issue will be closed and ignored if I do not fill this form properly

**Comment by sumghai** [comment]
Ew, that modlist you copied straight out of HugsLib had a bunch of irrelevant version numbers of subassemblies. In the future, please specify the actual version numbers of the mods itself, not what HugsLib generates in its report.

I loaded the following mods in my own game:
- Harmony 1.3.0.0
- Core 1.3.3389
- Ideology 1.3.3389
- HugsLib 9.0.1
- Replimat 1.3.4
- Vanilla Expanded Framework 130722 snapshot
- Vanilla Cooking Expanded 1.407
- Humanoid Alien Races 17 May 2022 Steam version
- Remote Tech 2.4.0
- Pawnmorpher 13 July 2022 Steam version

The debug log errors I got were:
- `Could not resolve cross-reference: No Verse.ThingDef named Mutasalt found to give to Verse.ThingDefCountClass (10x null)`, which looks like something to do with Mutasalt no longer being in the game when both Remote Tech and Pawnmorpher are active.
- No errors regarding Mutacheese
- A different `Config error in rxChunkSlagGold: has smeltProducts but has smeltable=false`

No errors appear when Remote Tech is disabled.

However, the errors ***do*** appear when Remote Tech is active, but with Replimat is ***disabled***.

Since we can take Replimat out of the equation, the problem seems to be solely between Pawnmorpher and Remote Tech themselves. Please contact the latter two mods' respective authors to resolve this issue.
